spring:
  datasource:
    url: jdbc:h2:mem:mailbox;INIT=RUNSCRIPT FROM './src/main/resources/schema/schema.sql'
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console.enabled: true
