spring:
  datasource:
    url: jdbc:h2:mem:mailbox;INIT=RUNSCRIPT FROM './src/main/resources/schema/schema.sql'
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console.enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
mail-sender:
  host: smtp.gmail.com
  port: 587
  username:
  password:
  protocol: smtp
  auth: true
  starttls-enable: true
  debug: true
